[build-system]
requires = [
"setuptools",
"wheel"
]
build-backend="setuptools.build_meta"
[project]
dependencies = ["ordered-set"]
[tool.setuptools.dynamic]
version = {attr = "observer_hooks.VERSION"}
readme = {file = ["README.md"]}
